config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :routes, only: [:index, :show]

  get '/near_by', to: 'welcome#near_by'
  get '/auth/twitter', as: :login
  get '/auth/twitter/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout
end

app/models/route.rb
class Route < Struct.new(:id, :short_name)
  attr_accessor :departure_time
end

app/models/stop.rb
class Stop < Struct.new(:id, :name)
end

app/models/stop_time.rb
class StopTime < Struct.new(:departure_time, :name, :stop_id, :near_by_path)
end

app/models/trip.rb
class Trip < Struct.new(:id, :stop_times)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  if Rails.env.test?
    NEXT_STOP = "http://localhost:3001/api/v1"
  else
    NEXT_STOP = "http://nextstopapi-1507.herokuapp.com/api/v1"
  end

  def search_response
    stop_id = params[:stop_id]
    @stop_name = params[:stop_name]
    departure_time = params[:departure_time]
    HTTParty.get("#{NEXT_STOP}/search", query: {stop_id: stop_id, departure_time: departure_time})
  end

  def departure_time(stop_time_json)
    Time.parse(stop_time_json['departure_time']).strftime('%l:%M %P')
  end

  def new_path(stop_time_json)
    {stop_id: stop_time_json['stop_id'], departure_time: stop_time_json['departure_time'], stop_name: stop_time_json['name']}
  end

  def new_route(route_json)
    Route.new(route_json['route_id'], route_json['route_short_name'])
  end

  def single_route
    route_id = params[:id]
    HTTParty.get("#{NEXT_STOP}/routes/#{route_id}")
  end

  def single_trip(trip_id)
    HTTParty.get("#{NEXT_STOP}/trips/#{trip_id}")
  end

  def routes
    HTTParty.get("#{NEXT_STOP}/routes")
  end

  def json_body(response)
    JSON.parse(response.body)
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  def index
    id, name = params[:route].split('_')
    @route = Route.new(id, name)
  end

  def show
    route_json = json_body(single_route)
    @route = new_route(route_json)

    @trips = route_json['trips'].first(3).map do |trip_json|
      trip_response = single_trip(trip_json['trip_id'])
      stop_times = json_body(trip_response)['stop_times'].map do |stop_time_json|
        path = near_by_path(new_path(stop_time_json))
        StopTime.new(departure_time(stop_time_json), stop_time_json['name'], stop_time_json['stop_id'], path)
      end
      Trip.new(trip_json['trip_id'], stop_times)
    end

    render json: @trips
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @routes = json_body(routes).map do |route_json|
      new_route(route_json)
    end
  end

  def near_by
    @routes = json_body(search_response).map do |route_json|
      route = new_route(route_json)
      route.departure_time = route_json['departure_time']
      route
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<nav id="my-navbar" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div id="my-navbar" class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href= <%= root_path %> >Next Stop</a>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NextStop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <%= yield %>
</body>
</html>

app/views/routes/index.html.erb
<h1 class="text-center">Route <%= @route.short_name %></h1><br>
<div id="trips">
  <div class="loading">
    <h2>Your trips are loading!</h2>
    <div class="meter animate">
      <span></span>
    </div>
  </div>
</div>

<%= hidden_field_tag "route", route_path(@route.id, format: :json) %>

<script id="tripTemplate" type="text/x-handlebars-template">
  <ul class="trip"></ul>
</script>

<script id="stopTimeTemplate" type="text/x-handlebars-template">
  <li class="stopTime">
    <div class="well">
      <div class="stopTime-name text-center">
        {{name}}
      </div>
      <div class="stopTime-time text-center">
        <a href="{{near_by_path}}">{{departure_time}}</a>
      </div>
    </div>
  </li>
</script>

<script>
  var routePath = $('[name=route]').val();
  var tripTemplate = Handlebars.compile($("#tripTemplate").html());
  var stopTimeTemplate = Handlebars.compile($("#stopTimeTemplate").html());
  var tripsElement = $('#trips');
  $.get(routePath)
      .success(function (trips) {

        $.each(trips, function (index, trip) {
          var renderedTrip = $(tripTemplate());

          $.each(trip.stop_times, function(index, stopTime) {
            var renderedStopTime = stopTimeTemplate(stopTime);
            renderedTrip.append($(renderedStopTime));
          });

          tripsElement.append(renderedTrip);
          $('.loading').hide();
        });

      });
</script>

app/views/welcome/index.html.erb
<div class="container">
  <h2 class="text-center">Welcome to Next Stop</h2>
  <div class="well">
    <h4 class="text-center">To get started, select a Route for Stop information.</h4>
    <h4 class="text-center">For transfer information, you can then select your preferred stop.</h4>
  </div>

  <div class="well">
    <div class="row text-center">
      <h3>Please Select a Route</h3>
      <%= form_tag(routes_path, method: :get) do %>
        <%= select_tag :route, options_from_collection_for_select(@routes, ->(route) {"#{route.id}_#{route.short_name}"}, :short_name), class: 'input-sm' %>
        <br><br>
        <%= submit_tag 'Submit', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/near_by.html.erb
<h2 class="text-center">Buses for <%= @stop_name %></h2>

<div class="container">
  <div class="well">
    <ul>
      <% @routes.each do |route| %>
        <li class="stopTime">
          <div class="stopTime-name">
            Route: <%= route.short_name %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>